### ISSUE TITLE
topaz is not using gpu

### ISSUE THREAD

**Issue by diffracteD** [tbepler/topaz#165]
Hi,
I installed topaz with conda and integrated with cryosparc. However, every time I'm trying to run some picking or denoising the topaz is falling back to cpu due to some reason.
Is there any way to identify why it is happening and fix this ? It's insanely slow over cpu.

Please suggest.
Thanks

**Comment by tbepler** [comment]
To help diagnose, we'll need some more detailed info. Does Topaz output any specific error or warning messages? Can you also share what package versions you have installed (e.g., the output of `conda list` if you are using conda) and what version of CUDA and CUDA drivers you have (e.g., the output of `nvidia-smi`)?

**Comment by tbepler** [comment]
This doesn't look like your topaz environment. I don't see topaz or pytorch on the list. Can you share your topaz conda environment packages?

**Comment by diffracteD** [comment]
My bad.
Here's what I get after topaz is sourced through conda.
```
(base) [user@gpu-02 ~]$ conda activate topaz
(topaz) [user@gpu-02 ~]$ conda list
# packages in environment at /home/abhisek/.conda/envs/topaz:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
blas                      1.0                         mkl  
ca-certificates           2022.4.26            h06a4308_0  
certifi                   2022.5.18.1      py39h06a4308_0  
cffi                      1.15.0           py39hd667e15_1  
cudatoolkit               11.6.0              hecad31d_10    conda-forge
daal4py                   2021.5.0         py39h78b71dc_0  
dal                       2021.5.1           h06a4308_803  
freetype                  2.10.4               h0708190_1    conda-forge
future                    0.18.2           py39hf3d152e_5    conda-forge
intel-openmp              2021.4.0          h06a4308_3561  
joblib                    1.1.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h166bdaf_1    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 11.2.0               h1234567_1  
libgfortran-ng            7.5.0               h14aa051_20    conda-forge
libgfortran4              7.5.0               h14aa051_20    conda-forge
libgomp                   11.2.0               h1234567_1  
libpng                    1.6.37               h21135ba_2    conda-forge
libstdcxx-ng              11.2.0               h1234567_1  
libtiff                   4.2.0                h85742a9_0  
libwebp-base              1.2.2                h7f98852_1    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py39h7e14d7c_0    conda-forge
mkl_fft                   1.3.1            py39h0c7bc48_1    conda-forge
mkl_random                1.2.2            py39hde0f152_0    conda-forge
mpi                       1.0                       mpich  
mpich                     3.3.2                hc856adb_0  
ncurses                   6.3                  h7f8727e_2  
ninja                     1.11.0               h924138e_0    conda-forge
numpy                     1.22.3           py39he7a7128_0  
numpy-base                1.22.3           py39hf524024_0  
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openssl                   1.1.1o               h7f8727e_0  
pandas                    1.4.2            py39h1832856_1    conda-forge
pillow                    7.2.0            py39h6f3857e_2    conda-forge
pip                       21.2.4           py39h06a4308_0  
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
python                    3.9.12               h12debd9_1  
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytorch                   1.10.2          cpu_py39hfa7516b_0  
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
readline                  8.1.2                h7f8727e_1  
scikit-learn              1.0.2            py39h51133e4_1  
scikit-learn-intelex      2021.5.0         py39h06a4308_0  
scipy                     1.7.3            py39hc147768_0  
setuptools                61.2.0           py39h06a4308_0  
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.38.3               hc218d9a_0  
tbb                       2021.5.0             hd09550d_0  
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tk                        8.6.12               h1ccaba5_0  
topaz                     0.2.4                      py_0    tbepler
torchvision               0.2.2                      py_3    pytorch
typing-extensions         4.2.0                hd8ed1ab_1    conda-forge
typing_extensions         4.2.0              pyha770c72_1    conda-forge
tzdata                    2022a                hda174b7_0  
wheel                     0.37.1             pyhd3eb1b0_0  
xz                        5.2.5                h7f8727e_1  
zlib                      1.2.12               h7f8727e_2  
zstd                      1.4.9                ha95c52a_0    conda-forge

```
Thanks

**Comment by tbepler** [comment]
It looks like the problem is that you have the CPU version of pytorch installed.

```
pytorch                   1.10.2          cpu_py39hfa7516b_0  
```

Take a look at the install instructions [here](https://pytorch.org/get-started/previous-versions/#linux-and-windows) for installing pytorch with CUDA support.

**Comment by diffracteD** [comment]
Hi, sorry I forgot to update the thread. This helped solve the issue. Thanks a lot !

**Comment by tbepler** [comment]
Glad that resolved it!
